app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.Text)
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref='user',lazy="dynamic")


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash, password)
    
    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'


class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255),index = True)
    category = db.Column(db.String(255), index = True)
    pitch = db.Column(db.Text)
    upvotes = db.Column(db.Integer, default=0)
    downvotes = db.Column(db.Integer, default=0)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref='pitch',lazy="dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, user_id):
        pitches = Pitch.query.filter_by(user_id=user_id).all()
        return pitches
    
    @classmethod
    def get_all_pitches(cls):
        pitches = Pitch.query.all()
        return pitches

    @classmethod
    def get_pitch(cls, pitch_id):
        pitch = Pitch.query.filter_by(id=pitch_id).one()
        return pitch

    def __repr__(self):
        return f'User {self.title}'


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.Text)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_all_comments(cls, pitch_id):
        pitches = Pitch.query.filter_by(pitch_id=pitch_id).all()
        return pitches

    def __repr__(self):
        return f'Comment {self.id}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.fields.core import SelectField
from wtforms.validators import Required

class CommentForm(FlaskForm):
    comment = TextAreaField('Add comment',validators=[Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
    category_choices = ['Product', 'Pickup', 'Interview']
    title = StringField('Title',validators=[Required()])
    category = SelectField('Category', choices = category_choices, validators = [Required()])
    pitch = TextAreaField('Pitch', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet, configure_uploads, IMAGES


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos', IMAGES)
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

     #Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
from flask.helpers import url_for
from werkzeug.utils import redirect
from flask import render_template, request, abort
from flask_login import login_required, current_user
from app.models import Comment, Pitch, User
from app.main.forms import CommentForm, PitchForm, UpdateProfile
from . import main
from .. import db, photos

# Views
@main.route("/")
def index():
    pitches = Pitch.get_all_pitches()
    return render_template("index.html", pitches=pitches)


@main.route("/my_pitches")
@login_required
def my_pitches():
    pitches = Pitch.get_pitches(current_user.id)
    return render_template("my_pitches.html", pitches=pitches)


@main.route("/pitch", methods=["GET", "POST"])
@login_required
def add_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        pitch = Pitch(
            title=form.title.data,
            category=form.category.data,
            pitch=form.pitch.data,
            user=current_user,
        )
        db.session.add(pitch)
        db.session.commit()
        return redirect(url_for("main.my_pitches"))

    title = "Add Pitch"
    return render_template("new_pitch.html", pitch_form=form, title=title)

@main.route("/pitch/comments/<int:id>", methods=['GET','POST'])
@login_required
def comments(id):
    form = CommentForm()
    pitch = Pitch.get_pitch(id)
    if request.method == 'GET':
        comments = pitch.comments
        return render_template("comments.html", comments=comments, user=current_user, comment_form=form)
    else:
        if form.validate_on_submit():
            comment = Comment(comment=form.comment.data, pitch=pitch, user_id=current_user.id)
            db.session.add(comment)
            db.session.commit()
            # refetch comments
            comments = pitch.comments
            # clear form since we are rendering same view
            form.comment.data = ""
            return render_template("comments.html", comments=comments, user=current_user, comment_form=form)


@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    pitches = Pitch.get_pitches(current_user.id)
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user, pitches=pitches)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))



@main.route('/pitch/<int:id>/vote/<vote>', methods=['GET','POST'])
@login_required
def vote(id, vote):
    pitch = Pitch.get_pitch(id)
    if vote == 'upvote':
        pitch.upvotes = pitch.upvotes + 1
    else:
        pitch.downvotes = pitch.downvotes + 1
    db.session.commit()
    return redirect(url_for('main.index'))

@main.route("/filter/<category>")
def filter_pitches(category):
    pitches = Pitch.query.filter_by(category = category).all()
    return render_template("index.html", pitches=pitches)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>One Minute Pitch</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">ONE MINUTE PITCH</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.my_pitches')}}">My Pitches</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.add_pitch')}}">Add Pitch</a>
                </li>
                {% endif %}
            </ul>
            <span class="my-2 my-lg-0 auth">
                {% if current_user.is_authenticated %}
                    <a class="nav-link " href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
                    <a class="nav-link " href="{{url_for('auth.logout')}}"><i class="fas fa-sign-in-alt"></i>&nbsp;
                        <strong>Sign Out</strong></a>
                {% else %}
                    <a class="nav-link " href="{{url_for('auth.login')}}"><i class="fas fa-sign-in-alt"></i>&nbsp;
                        <strong>Sign In</strong></a>
                    <a class="nav-link" href="{{url_for('auth.register')}}"><i class="fas fa-user-plus"></i></i>&nbsp;
                        <strong>Sign Up</strong></a>
                {% endif %}
            </span>
        </div>
    </nav>

    <div class="container-fluid">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/comments.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="card" style="width: 100%;">
        {% if comments.count() > 0 %}
          {% for comment in comments %}
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p>{{comment.comment}}.</p>
                <footer class="blockquote-footer">{{user.username}}</footer>
              </blockquote>
            </div>
          {% endfor %}
        {% else %}
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <footer class="blockquote-footer">No comments yet!</footer>
            </blockquote>
          </div>
        {% endif %}
      </div>
    </div>
    <div class="col-md-4">{{wtf.quick_form(comment_form)}}</div>
  </div>
</div>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}
    {% block content %}
        <h1>WHOOPS we can't find your page</h1>
    {% endblock%}

app/templates/index.html
{% extends "base.html" %} {% block body %}

<div class="col-md-12">
  <div class="pitches_tabs">
    <ul class="nav nav-tabs">
      <li class="nav-item tabp">
        <a class="nav-link linkp" aria-current="page" href="/">All</a>
      </li>
      <li class="nav-item tabp">
        <a class="nav-link linkp" href="/filter/Product">Product</a>
      </li>
      <li class="nav-item tabp">
        <a class="nav-link linkp" href="/filter/Pickup">Pickup</a>
      </li>
      <li class="nav-item tabp">
        <a class="nav-link linkp" href="/filter/Interview">Interview</a>
      </li>
    </ul>
  </div>

  <div class="pitches">
    {% for pitch in pitches %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ pitch.title }}</h5>
        <p class="card-text">{{ pitch.pitch }}</p>
      </div>
      <button type="button" class="btn commentbtn">
        <a href="/pitch/comments/{{pitch.id}}">Comment</a>
      </button>
      <div class="card-footer">
        <small class="text-muted">Category: {{ pitch.category }}</small>
        <span class="text-muted vote">
          <span class="upvote">
            <a href="/pitch/{{pitch.id}}/vote/upvote"><i class="fa fa-fw fa-thumbs-up"></i>
              {{ pitch.upvotes }}
            </a>
          </span>
          <span class="downvote">
            <a href="/pitch/{{pitch.id}}/vote/downvote"><i class="fa fa-fw fa-thumbs-down"></i>
              {{ pitch.downvotes }}
            </a>
          </span>
        </span>
      </div>
    </div>

    {% endfor %}
  </div>
</div>

{% endblock %}

app/templates/my_pitches.html
{% extends "base.html" %} {% block body %}

<div class="col-md-12">
  <div class="pitches">
    {% for pitch in pitches %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ pitch.title }}</h5>
        <p class="card-text">{{ pitch.pitch }}</p>
      </div>
      <button type="button" class="btn commentbtn">
        <a href="/pitch/comments/{{pitch.id}}">Comment</a>
      </button>
      <div class="card-footer">
        <small class="text-muted">Category: {{ pitch.category }}</small>
        <span class="text-muted vote">
          <span class="upvote"
            ><i class="fa fa-fw fa-thumbs-up"></i> {{ pitch.upvotes }}</span
          >
          <span class="downvote"
            ><i class="fa fa-fw fa-thumbs-down"></i> {{ pitch.downvotes }}</span
          >
        </span>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block body %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

{{wtf.quick_form(pitch_form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%} {% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card" style="width: 18rem">
        {% if user.profile_pic_path %}
        <img
          src="{{url_for('static',filename=user.profile_pic_path)}}"
          alt=""
          class="img-thumbnail"
        />
        {%else%}
        <p>No profile picture</p>
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{user.username| capitalize}}</h5>
          <!--Displaying user bio-->
          {% if user.bio %}
          <p>{{user.bio}}</p>
          {%else%}
          <p>{{user.username| capitalize}} has no bio</p>
          {% endif %} {% if user == current_user %}
          <a href="{{url_for('main.update_profile',uname=user.username)}}"
            >Edit profile</a
          >
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-md-6">
      {% if user == current_user %}
      <form
        action="{{url_for('main.update_pic',uname=user.username)}}"
        method="post"
        enctype="multipart/form-data"
        style="margin-top: 2rem;"
      >
        <label for="photo">Update profile photo</label>
        <input id="photo" type="file" name="photo" class="form-control" required />
        <input type="submit" style="margin-top: 1rem;"/>
      </form>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="pitches">
        {% for pitch in pitches %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ pitch.title }}</h5>
            <p class="card-text">{{ pitch.pitch }}</p>
          </div>
          <button type="button" class="btn commentbtn">
            <a href="/pitch/comments/{{pitch.id}}">Comment</a>
          </button>
          <div class="card-footer">
            <small class="text-muted">Category: {{ pitch.category }}</small>
            <span class="text-muted vote">
              <span class="upvote"
                ><i class="fa fa-fw fa-thumbs-up"></i> {{ pitch.upvotes }}</span
              >
              <span class="downvote"
                ><i class="fa fa-fw fa-thumbs-down"></i> {{ pitch.downvotes }}</span
              >
            </span>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block body %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}